### PR TITLE
[DO NOT MERGE: UNDER API REVIEW] Jennyf/b2c sample protoype

### PR DESCRIPTION
**Pull request by jennyf19**
Any and all feedback welcome. The public api has not been determined either, so feel free to offer other suggestions.

### CODE REVIEW

**Comment by jmprieur** [comment]
@jennyf19 I guess we mark this as do not merge for the moment?

**Comment by jennyf19** [comment]
@jmprieur good idea. i changed the title.

**Comment by jmprieur** [comment]
@valnav : FYI this pending the API review

**Comment by jennyf19** [comment]
not happening now

**Pull request closed without merging**
