### PR TITLE
Updating to MSAL 1.1.3-preview and Xamarin.Android.Support to 27.0.2 …

### PR DESCRIPTION
**Pull request by jennyf19**
…and MonoAndroid8.1

### CODE REVIEW

**Comment by codemillmatt** [comment]
@jennyf19 - should we remove the AsyncUsageAnalyzer from the projects before merging?

**Comment by jennyf19** [comment]
@msoucoup done...should have not committed that in the first place. :/

---
In reply to: [393115818](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/pull/51#issuecomment-393115818) [](ancestors = 393115818)

**Comment by codemillmatt** [comment]
lgtm ... 👍 👍

**Comment by codemillmatt** [comment]
@jennyf19 - reverting this PR 😢  Getting an exception on iOS (Droid is OK):

```
  at Microsoft.Identity.Client.TokenCacheAccessor.Remove (System.String key, System.String service) [0x00055] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.TokenCacheAccessor.SetValueForKey (System.String key, System.String value, System.String service) [0x00000] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.TokenCacheAccessor.SaveAccessToken (System.String cacheKey, System.String item) [0x00000] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.Internal.Telemetry.TelemetryTokenCacheAccessor.SaveAccessToken (System.String cacheKey, System.String item, Microsoft.Identity.Client.Internal.RequestContext requestContext) [0x00023] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.TokenCache.SaveAccessAndRefreshToken (Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters requestParams, Microsoft.Identity.Client.Internal.OAuth2.TokenResponse response) [0x00291] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.SaveTokenResponseToCache () [0x001a8] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.PostTokenRequest () [0x00008] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase+<RunAsync>d__33.MoveNext () [0x00360] in <7f73819fd99b45669100adda813d89e4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <8a48725212864358a4554e3196f5ca74>:0 
  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenForUserCommonAsync>d__18.MoveNext () [0x000d2] in <7f73819fd99b45669100adda813d89e4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <8a48725212864358a4554e3196f5ca74>:0 
  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenAsync>d__11.MoveNext () [0x000a0] in <7f73819fd99b45669100adda813d89e4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <8a48725212864358a4554e3196f5ca74>:0 
  at UserDetailsClient.Core.MainPage+<OnSignInSignOut>d__2.MoveNext () [0x00083] in /Users/msoucoup/Projects/active-directory-b2c-xamarin-native/UserDetailsClient/UserDetailsClient.Core/MainPage.xaml.cs:46 
```

**Comment by codemillmatt** [comment]
Tagging @jmprieur

**Comment by jennyf19** [comment]
@codemillmatt @jmprieur working on a fix now. thanks.

**Comment by jennyf19** [comment]
@codemillmatt @jmprieur Fixed in [1.1.4-preview ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/570)

I'll send a new PR tomorrow w/the update

**Pull request merged**
